#! /bin/sh

die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR="$(dirname "$(readlink -f "$0")")"

[ -d /cache/arch-pkgs ] || sudo mkdir /cache/arch-pkgs
[ -d /cache/flathub-pkgs ] || sudo mkdir /cache/flathub-pkgs
[ -d /cache/proxy ] || sudo mkdir /cache/proxy
[ -d /cache/aur ] || sudo mkdir /cache/aur
[ -d /cache/aur/metadata ] || sudo mkdir /cache/aur/metadata
[ -d /cache/aur/repos ] || sudo mkdir /cache/aur/repos

sudo chown -R 1654:1654 /cache/aur/metadata || die "Could not set aur/metadata permissions"
sudo chown -R 1654:1654 /cache/aur/repos || die "Could not set aur/repos permissions"
sudo chown -R 1654:1654 /cache/proxy || die "Could not set proxy permissions"


git pull
[ -f /etc/pacman.d/chaotic-mirrorlist ] || die "No /etc/pacman.d/chaotic-mirrorlist"

reflector --protocol https --country GB --fastest 20 --sort age --save "$BASEDIR/mirrorlist"

cp /etc/pacman.d/chaotic-mirrorlist "$BASEDIR/chaotic-mirrorlist"

[ -f "$BASEDIR/certs/aur.local.pfx" ] || "$BASEDIR/certs/generate" aur.local
[ -f "$BASEDIR/certs/aur.local.pfx" ] || die "No aur cert"

# Ensure Pfx is readable
chmod 644 "$BASEDIR/certs/aur.local.pfx"
#sudo chown -R 10001:65533 /cache/arch-pkgs || die "Could not set npm permissions"

sudo docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/cache/aur/metadata \
  cache-aur-metadata

sudo docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/cache/aur/repos \
  cache-aur-repos

sudo docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/cache/proxy \
  cache-proxy

sudo docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/cache/flathub-pkgs \
  cache-flathub

sudo docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/cache/arch-pkgs \
  cache-pacoloco

sudo docker compose pull || die "Could not pull images"
sudo docker compose build || die "Could not build images"

sudo docker compose up -d --remove-orphans || die "Could not start containers"
